import React from 'react';

const AboutUs = () => {
    return (
        <section id="about">
            <h2>About Us</h2>
            <p>Feel free to reach out to us!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque rerum minus itaque voluptates error obcaecati qui deleniti assumenda, sequi sed cumque et similique tempora nihil molestias laudantium ea sunt! Facilis.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime pariatur aspernatur reiciendis? Fugiat earum eius ipsam autem voluptates eveniet officia? Quisquam at mollitia officia sit molestias ea ab nisi harum.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Necessitatibus ratione officia corrupti illum voluptatem sint aliquid, delectus amet distinctio laudantium consectetur doloribus provident sed ducimus modi veniam rem reiciendis? Non. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, impedit iste aliquam, totam esse perspiciatis eius temporibus necessitatibus aperiam labore expedita maiores obcaecati sequi? Et unde blanditiis quisquam ad totam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut sequi unde, minima enim, nemo cum porro est id quos ullam sint voluptate quod reiciendis quis magnam ab. Fuga, rem? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad dolorum earum adipisci amet enim pariatur expedita neque! Commodi, atque nemo amet iure officia, deserunt ex temporibus, odio laborum dolore provident? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem illum tenetur voluptatibus animi ratione? Minus sapiente quia in eius temporibus saepe alias beatae nulla odit, architecto eum repellendus veritatis cum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti reprehenderit hic harum, adipisci molestias placeat iusto, modi necessitatibus nulla minima voluptas culpa dicta delectus reiciendis! Fugiat ipsa molestias qui earum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Est dignissimos minus ipsa pariatur harum, eaque animi quos eveniet earum blanditiis assumenda aliquam, tempora aperiam necessitatibus accusantium et quod quibusdam debitis! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non ipsa et saepe laboriosam atque error, eum dignissimos in eligendi fugiat recusandae nam ad ab harum obcaecati quidem eos adipisci cum. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Error, distinctio. Sapiente perspiciatis dolorum libero odio incidunt, consectetur commodi unde ex aut, corrupti, inventore exercitationem eligendi qui nisi ipsam est? Incidunt! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis pariatur, eligendi mollitia et voluptate at cumque velit nesciunt minima impedit adipisci neque repellendus eveniet expedita, nam asperiores accusamus provident illo. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam iure minima, at eligendi debitis aspernatur quidem necessitatibus. Accusamus accusantium recusandae temporibus dolores magnam, expedita inventore, aperiam libero laboriosam, numquam enim!</p>

        </section>
    );
}

export default AboutUs;